spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/red_blue?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: ${DB_TEST_USER_NAME}
    password: ${DB_TEST_PASSWORD}

logging:
  level:
    org:
      springframework:
        security: DEBUG

mybatis:
  mapper-locations: classpath:/mapper/*.xml